work_dir: temp
name_field: name

tasks:
- name: xxxx
  kind: samples
  parallel: 2
  block: false
  command: |
    echo {{.name}}
    sleep 10

objects:
  samples:
  - {name: a1}
  - {name: a2}
  - {name: a3}
